---
version: 2

jobs:
  build:
    working_directory: /go/src/github.com/nicholasjackson/grpc-consul-resolver
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go mod download
      - run: make build
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/nicholasjackson/grpc-consul-resolver

  test:
    working_directory: /go/src/github.com/nicholasjackson/grpc-consul-resolver
    docker:
      - image: circleci/golang:1.11
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: go mod download
      - run: make test_unit

  functional:
    working_directory: /go/src/github.com/nicholasjackson/grpc-consul-resolver
    docker:
      - image: circleci/golang:1.11
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: go mod download
      - run:
          name: install and start consul
          command: |
            wget https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip
            unzip consul_1.3.0_linux_amd64.zip
            sudo mv consul /usr/bin
            consul agent -dev -config-file=./functional_tests/consul.hcl 2>"/tmp/consul.out" &
            sleep 3
      - run: make test_functional

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - functional:
          requires:
            - build
            - test
